import { StyleSheet } from "react-native";
let blueColor = "#F54336";
export default StyleSheet.create({
  mainBody: {
    // marginHorizontal: 20,
    height: "100%",
    // marginBottom: 50
    // position: "relative",
    backgroundColor: "#f2f2f2",
  },
  topFilter: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
  },
  filter: {},
  topFilterSec: {
    width: 15,
    height: 15,
    marginRight: 5,
    backgroundColor: "white",
    alignSelf: "center",
    display: "flex",
    alignContent: "center",
    elevation: 5,
    shadowColor: "red",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 5,
  },
  topSearchBar: {
    position: "relative",
    marginHorizontal: 10,
    // elevation: 5,
    // shadowColor: "blue",
    // shadowOffset: { width: 0, height: 10 },
    // shadowOpacity: 1,
    // shadowRadius: 5,
  },
  topSearchBarResult: {
    width: "100%",
    height: "100%",
    zIndex: 1,
  },
  searchLocationResult: {
    paddingHorizontal: 15,
    display: "flex",
  },
  eachLocation: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderTopWidth: 1,
    backgroundColor: "#FFFAFA",
  },
  singleLocationName: {
    color: blueColor,
    fontSize: 15,
  },
  topPhotographers: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    backgroundColor: "white",
    marginTop: 10,
    padding: 10,
    borderRadius: 5,
    marginHorizontal: 20,
  },
  singlePhotographerBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",

    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
    // backgroundColor: "red",
  },

  photographerImgBox: {
    display: "flex",
    flexDirection: "row",
  },
  userDetailsBox: {
    width: "100%",
    flexShrink: 1,
  },
  photographerName: {
    fontSize: 20,
    textTransform: "capitalize",
  },
  userDetailsSec: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    marginVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 10,
  },
  detailsBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: "40%",
    marginRight: 5,
  },
  ratigIconImg: {
    fontSize: 15,
  },
  ratingNumber: {
    marginLeft: 3,
    fontSize: 15,
  },
  photographerImg: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  photographerBookSection: {
    display: "flex",
    flexDirection: "row",
    marginHorizontal: 5,
    alignItems: "center",
    marginTop: 5,
  },
  btnBox: {
    marginLeft: "auto",
  },
  startingPrice: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 5,
  },
  customBtn: {
    color: blueColor,
    paddingVertical: 5,
    paddingHorizontal: 15,
    textAlign: "center",
    borderWidth: 1,
    borderColor: blueColor,
  },
  startingPriceNumber: {
    color: blueColor,
    fontSize: 17,
  },
  custominputBox: {
    borderWidth: 1,
    marginBottom: 10,
    borderColor: "#13191d42",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  custominputBoxTop: {
    borderWidth: 1,
    borderColor: "red",
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "white",
    marginVertical: 5,
  },
  showFilterResultBox: {
    backgroundColor: blueColor,
    width: 120,
    alignSelf: "flex-end",
    paddingVertical: 5,
    borderRadius: 4,
  },
  showFilterText: {
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
  },

  dateDesign: {
    color: "white",
  },
  selectDateBox: {
    display: "flex",
    flexDirection: "row",
  },
  noPhotographerAvail: {
    justifyContent: "center",
    alignItems: "center",
  },
  noPhotographerText: {
    // flex: 3,
    fontSize: 20,
    paddingTop: 20,
    justifyContent: "center",
    alignItems: "center",
    color: blueColor,
  },

  sortText: {
    fontSize: 17,
    textTransform: "capitalize",
  },
  bookFormDesign: {
    marginHorizontal: 30,
  },
  messageBox: {
    height: 100,
    textAlignVertical: "top",
  },
  userTopInfo: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
  },
  smallProfilePic: {
    width: 80,
    height: 80,
    borderRadius: 50,
  },
  userTopName: {
    fontWeight: "700",
    fontSize: 20,
    marginLeft: 5,
    color: blueColor,
  },
  bookFormBox: {
    marginTop: 15,
    marginHorizontal: 20,
  },
  newOrderBox: {
    backgroundColor: blueColor,
    paddingVertical: 15,
    marginTop: 15,
  },
  bookNowBtnText: {
    fontSize: 17,
    textAlign: "center",
    fontWeight: "700",
    color: "white",
  },
  splzBtnText: {
    color: blueColor,
    fontSize: 20,
  },
  customSplzBtn: {
    width: "49%",
    marginBottom: 10,
    padding: 15,
    borderWidth: 1,
    borderColor: blueColor,
    marginRight: 5,
    position: "relative",
    borderRadius: 6,
    overflow: "hidden",
    // backgroundColor: "#ebeef9",
  },
  rating: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: blueColor,
    padding: 2,
  },
  socialIcon: {
    color: blueColor,
    fontSize: 12,
  },
  orderPriceBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  orderPriceText: {
    fontSize: 18,
    marginLeft: 5,
  },
  ratingText: {
    fontSize: 13,
    marginLeft: 2,
    color: "white",
  },
  splzFlat: {
    paddingHorizontal: 10,
    margin: "auto",
  },
  backSplzBtn: {
    color: "white",
    fontSize: 18,
    marginLeft: 5,
  },
  backBtnTouch: {
    backgroundColor: blueColor,
    display: "flex",
    flexDirection: "row",
    textAlign: "center",
    alignItems: "center",
    width: 120,
    padding: 5,
    marginBottom: 10,
    borderRadius: 4,
    justifyContent: "center",
    color: "white",
  },
  socialIconBack: {
    color: "white",
    fontSize: 18,
  },
  backSectionBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  backRightBox: {
    marginLeft: "auto",
  },
  filterBoxDesign: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
    borderRightColor: "#13191d42",
    backgroundColor: "white",
    width: "50%",
    paddingVertical: 15,
  },
  filterBox: {
    backgroundColor: "white",
    elevation: 5,
    shadowColor: "blue",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 5,
    borderRadius: 5,
    height: "100%",
    display: "flex",
    flexDirection: "row",
  },
  topFilderSection: {
    flex: 1,
  },
  leftMenu: {
    backgroundColor: "grey",
    width: "30%",
    zIndex: 0,
  },
  leftMenuProp: {
    height: 50,
    backgroundColor: "red",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 0,
  },
  rightMenuProp: {
    width: "100%",
    padding: 10,
    maxHeight: "70%",
  },
  footerFilterAction: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    zIndex: 1,
    display: "flex",
    flexDirection: "row",
    backgroundColor: "white",
    padding: 10,
    elevation: 5,
    shadowColor: "blue",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 5,
    borderTopColor: blueColor,
    borderTopWidth: 0.5,
  },
  hiddenFilterBox: {
    backgroundColor: blueColor,
    paddingVertical: 12,
    paddingHorizontal: 50,
    marginLeft: "auto",
    borderRadius: 4,
  },
  hiddenClearBox: {
    backgroundColor: "grey",
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 4,
  },
  findNearByPhotographer: {},
  topFindNearBox: {
    backgroundColor: blueColor,
    paddingVertical: 10,
    paddingHorizontal: 40,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: blueColor,
  },
  nearPhotoGrapherIcon: {
    fontSize: 15,
    marginRight: 5,
    color: "white",
  },
  cameraIcon: {
    fontSize: 50,
    color: "#757575",
    textAlign: "center",
  },
  selectItem: {
    backgroundColor: blueColor,
    borderColor: blueColor,
  },
  bottomProceed: {
    position: "absolute",
    width: "100%",
    bottom: 0,
    zIndex: 1,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 5,
  },
  proceedBtn: {
    backgroundColor: blueColor,
    paddingVertical: 15,
    marginTop: 15,
    display: "flex",
    flexDirection: "row",
    textAlign: "center",
    alignItems: "center",
  },
  proceesIconStyle: {
    color: "white",
    fontSize: 18,
  },
  imageBox: {
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  photographerAvatar: {
    alignSelf: "center",
  },
  userProfileName: {
    textAlign: "center",
    marginVertical: 7,
    fontSize: 18,
  },
  photographerSocial: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  socialBtn: {
    color: blueColor,
    fontSize: 20,
  },
  socialView: {
    backgroundColor: "#e7eaed",
    marginRight: 5,
    width: 40,
    height: 40,
    borderRadius: 3,
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  currentUserPhotoes: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 15,
  },
  usersGallary: {
    backgroundColor: "#e7eaed",
    paddingVertical: 5,
    paddingHorizontal: 25,
    borderRadius: 20,
    marginRight: 15,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  usersGallaryText: {
    textTransform: "capitalize",
    marginLeft: 5,
  },
  bannerBg: {
    maxHeight: 180,
    zIndex: 0,
    // flex: 1,
  },
  bannerBgImg: {
    height: "100%",
    width: "100%",
  },
  bookFormDesigns: {
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    backgroundColor: "white",
    zIndex: 0,
    // marginTop: -50,
    overflow: "hidden",
  },
  imageBoxForm: {
    // backgroundColor: "transparent",
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  submitOrder: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: blueColor,
    alignItems: "center",
    // justifyContent: "center",
    justifyContent: "space-around",
  },
  amountDesign: {
    color: "white",
    fontSize: 18,
  },
  orderNowBox: {
    // justifyContent: "flex-end",
    marginTop: 0,
  },
  bottomAmount: {
    justifyContent: "space-around",
  },
  sortPhotographerBox: {
    backgroundColor: "#2424247d",
    position: "absolute",
    // top: 0,
    bottom: 0,
    width: "100%",
    flex: 1,
  },
  sortPhotographer: {
    // position: "absolute",
    backgroundColor: "white",
  },
  sortPopUpBox: {
    width: "100%",
  },
  commonSortSec: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  sortHead: {
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#00000042",
    paddingVertical: 10,
  },
  sortText: {
    textTransform: "uppercase",
  },
  radioBtn: {
    marginLeft: "auto",
  },
});
