import { StyleSheet } from "react-native";
let blueColor = "#F54336";
let deepBlue = "#0d276b";
export default StyleSheet.create({
  mainBody: {
    position: "relative",
    height: "100%",
    backgroundColor: "#f7f7ff",
  },
  profileDetails: {
    paddingTop: 20,
    paddingBottom: 10,
  },
  profileImgBox: {
    display: "flex",
    alignItems: "center",
  },
  profileDetailsBox: {
    marginHorizontal: 20,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignSelf: "center",
  },
  userDetailsImg: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 1,
  },
  myDashboard: {
    marginHorizontal: 20,
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 15,
  },
  userName: {
    fontSize: 18,
    textTransform: "capitalize",
    color: deepBlue,
  },
  userNameEdit: {
    fontSize: 18,
    color: deepBlue,
  },
  userLocation: {
    display: "flex",
    flexDirection: "row",
  },
  locationArea: {
    textTransform: "capitalize",
    marginRight: 10,
    fontSize: 16,
    color: deepBlue,
  },
  userDescript: {},
  userEarning: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  userEarningMoney: {
    marginLeft: 3,
    fontSize: 18,
    color: deepBlue,
  },
  rupee: {
    height: 15,
    width: 15,
  },
  userPhotoDetails: {
    marginTop: 10,
    marginHorizontal: 20,
    backgroundColor: "white",
    padding: 10,
    elevation: 5,
    shadowColor: "blue",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 5,
  },
  userLeftDetails: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  userOrderDetailsUl: {
    borderBottomWidth: 1,
    borderBottomColor: "#bac8d3",
  },
  userDetailsLi: {
    paddingHorizontal: 15,
    paddingVertical: 20,
    // borderBottomWidth: 1,
    // borderBottomColor: "#bac8d3",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  // userIcon: {
  //   opacity: 0.7,
  //   width: 25,
  //   height: 25,
  // },
  userIconBox: {
    width: 40,
    alignSelf: "center",
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
  },
  userTypeText: {
    fontSize: 16,
    marginLeft: 15,
    opacity: 0.67,
  },
  profileHero: {
    width: "100%",
    height: 170,
    alignSelf: "center",
  },
  profileHeroImg: {
    alignSelf: "center",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    width: "100%",
    height: "100%",
  },
  bannerProfile: {
    marginHorizontal: 10,
  },
  smallProfileBox: {
    // position: "absolute",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
    // bottom: 5,
    zIndex: 1111,
    marginLeft: 15,
  },
  smallProfilePic: {
    position: "relative",
    top: -20,
  },
  profileDetails: {
    marginLeft: 20,
    position: "relative",
  },
  userNameActualName: {
    fontSize: 22,
    fontWeight: "bold",
    color: deepBlue,
  },
  socialProfiles: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  socialProfilesBox: {
    paddingHorizontal: 15,
    backgroundColor: "red",
  },
  socialIcon: {
    textAlign: "center",
    color: "#3b5998",
    fontSize: 25,
  },
  specialistIn: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  expertIn: {
    backgroundColor: "#e5eeff",
    marginRight: 10,
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 30,
    color: "#8697be",
    // fontWeight:"bold",
    fontSize: 15,
    textTransform: "capitalize",
    color: deepBlue,
  },
  showFilterResultBox: {
    alignSelf: "center",
    // marginTop: 7
  },
  bookNowBigBtn: {
    backgroundColor: blueColor,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: 250,
    alignSelf: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 4,
    justifyContent: "center",
    marginVertical: 10,
  },
  socialIconBookNow: {
    fontSize: 20,
    color: "white",
  },
  showFilterText: {
    color: "white",
    textAlign: "center",
    borderRadius: 5,
    fontSize: 20,
    paddingHorizontal: 10,
  },
  eachImage: {
    width: "32.3%",
    margin: 2,
    borderWidth: 2,
    borderColor: "#F54336",
  },
  loadMore: {
    backgroundColor: "red",
  },
  topHeaderAvatar: {
    height: 55,
    width: 55,
    borderRadius: 50,
  },
  topHeaderIcons: {
    color: "red",
    fontSize: 20,
  },
  topHeaderBar: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 3,
    alignItems: "center",
  },
  rightTopbarHeader: {
    marginLeft: "auto",
  },
  headerProfile: {
    marginHorizontal: 15,
  },
  uploadImageType: {
    backgroundColor: "#f8f9fab0",
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
  },
  uploadAction: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  actionAlert: {
    backgroundColor: "white",
    shadowColor: "#000",
    width: 250,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  eachActionSec: {},
  popUpClose: {
    marginLeft: "auto",
    width: 25,
    height: 25,
    position: "absolute",
    top: 7,
    right: 7,
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "green",
  },
  actionUploadTopHeader: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#dee2e6",
    paddingHorizontal: 15,
    paddingVertical: 15,
    alignItems: "center",
  },
  justUploadedMainBox: {},
  justUploadedImgBox: {
    width: 150,
    height: 150,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  justUploadedImg: {
    width: "100%",
    height: "100%",
  },
  imageBoxForm: {
    marginHorizontal: 15,
    marginVertical: 15,
  },
  imageBoxFormEachSection: {
    position: "relative",
  },
  formboxAfterFirst: {
    marginVertical: 10,
  },
  labelEachDeg: {
    position: "absolute",
    top: -10,
    left: 10,
    backgroundColor: "white",
    zIndex: 1,
    paddingHorizontal: 3,
  },
  imageboxFormInput: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 2,
    height: 40,
    borderColor: blueColor,
  },
  pickerSelectStyles: {
    backgroundColor: "red",
  },
  labelName: {
    textTransform: "capitalize",
  },
  postImageSec: {
    backgroundColor: blueColor,
    width: 150,
    marginLeft: "auto",
    borderRadius: 5,
  },
  postImageBtnText: {
    color: "white",
    textAlign: "center",
    textTransform: "capitalize",
    paddingVertical: 10,
    fontSize: 18,
  },
  commonFlex: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: 5,
  },
  eachSetting: {},
  settingText: {
    textTransform: "capitalize",
  },
  settingTextBox: {
    marginLeft: 5,
  },
  securityModalBox: {
    flex: 1,
  },
  changePassBtnBox: {
    // marginHorizontal: 15,
    marginBottom: 5,
  },
  changePassBtn: {
    backgroundColor: blueColor,
  },
  passChangeSuccessBox: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  passChangeSuccessText: {
    fontSize: 17,
    marginBottom: 3,
  },

  //Edit Profile
  editIcon: {
    position: "absolute",
    bottom: 0,
    right: 10,
    backgroundColor: "#d6d6d6",
    padding: 5,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
  editUserProfileInfo: {
    marginVertical: 15,
  },
  editDetailsText: {
    fontSize: 20,
    color: blueColor,
  },
  editProfileBoxEach: {
    alignItems: "center",
  },
  iconContainerEdit: {
    marginRight: 5,
    opacity: 0.7,
  },
  editModalBox: {
    // alignItems: "center",
    backgroundColor: "white",
    width: "80%",
    height: "auto",
    maxHeight: 350,
    borderRadius: 5,
    position: "relative",
    padding: 5,
  },
  editChangesBox: {
    paddingVertical: 10,
  },
  custominputBox: {
    borderWidth: 1,
    borderColor: blueColor,
    paddingHorizontal: 5,
    marginHorizontal: 10,
    marginVertical: 10,
    height: 45,
    borderRadius: 4,
  },
  editActonText: {
    fontSize: 17,
    textAlign: "center",
    paddingVertical: 10,
  },
  customModelBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",

    backgroundColor: "#00000094",
  },
  btnContainerUpdate: {
    maxWidth: 250,
    marginLeft: "auto",
    marginRight: 10,
    width: "auto",
  },
  updateBtnStyles: {
    paddingHorizontal: 15,
    color: blueColor,
  },
  updateBoxBtnBottom: {
    // flex: 1,
    justifyContent: "flex-end",
    alignItems: "baseline",
    marginBottom: 10,
  },
  modalBoxTopHader: {
    flexDirection: "row",
    // justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 10,
  },
  closeModalIcon: {
    position: "absolute",
    right: -20,
    top: -5,
    height: 30,
    width: 30,
  },
  datePickerColor: {
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
  },
  activityProgressBox: {
    justifyContent: "center",
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: blueColor,
    borderRadius: 20,
    padding: 1,
  },
  activityBoxDesign: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  inner: {
    width: "100%",
    height: 30,
    borderRadius: 20,
    backgroundColor: "green",
  },
  label: {
    fontSize: 15,
    color: "black",
    position: "absolute",
    zIndex: 1,
    alignSelf: "center",
  },
  animationProgressSection: {
    flex: 1,
    backgroundColor: "#bfbbbbde",
    justifyContent: "center",
  },
  activityBoxType: {
    justifyContent: "center",
    alignItems: "center",
  },
  ifActivitiShow: {
    justifyContent: "center",
  },
  activitiBoxWIthShadow: {
    backgroundColor: "white",
    height: 60,
    width: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignSelf: "center",
  },
  uploadingText: {
    textAlign: "center",
    marginTop: 5,
    fontSize: 18,
    color: blueColor,
  },
  otpModal: {
    flex: 1,
    justifyContent: "center",
    textAlign: "center",
    alignSelf: "center",
  },
  otpDesignBox: {
    backgroundColor: "white",
    paddingHorizontal: 35,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 30,
  },
  otpBox: {
    justifyContent: "flex-end",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 10,
  },
  otpBoxEach: {
    borderWidth: 1,
    borderColor: blueColor,
    width: 40,
    height: 40,
    marginRight: 10,
    textAlign: "center",
  },
  enterOTPText: {
    marginBottom: 10,
  },
  verificationMainText: {
    textTransform: "capitalize",
    fontSize: 25,
  },
  recendNumber: {
    paddingVertical: 5,
  },
  //Client Order Page Design
  singleOrderDetails: {
    position: "relative",
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    backgroundColor: "white",
    elevation: 3,
    marginVertical: 5,
    borderRadius: 10,
  },
  avatar: {
    width: 50,
    height: 50,
    padding: 2,
    borderWidth: 2,
    borderRadius: 25,
    borderColor: blueColor,
  },
  activeStatus: {
    height: 15,
    width: 15,
    borderRadius: 7.5,
    zIndex: 1,
    position: "absolute",
    right: 3,
    top: 3,
  },
  hiredUserLeft: {
    // width: 90,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  hiredAvatar: {
    width: "100%",
    height: "100%",
    borderRadius: 25,
  },
  hiredUserLeft: {
    // width: 90,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  bookieName: {
    fontSize: 17,
    fontFamily: "ubuntu-medium",
  },
  hiredUserRight: {
    marginLeft: 10,
    // backgroundColor: "red",
    width: "90%",
    marginTop: 5,
  },
  headerDetails: {
    // display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 3,
  },
  orderPageIcon: {
    color: blueColor,
    marginRight: 5,
  },
});
